# Generated by Django 3.2.5 on 2022-02-20 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='书号')),
                ('name', models.CharField(max_length=60, verbose_name='书名')),
                ('author', models.CharField(max_length=60, verbose_name='作者')),
                ('publisher', models.CharField(max_length=60, verbose_name='出版社')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可借')),
            ],
            options={
                'verbose_name': '书目',
                'verbose_name_plural': '书目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('borrow_time', models.DateTimeField(default=datetime.datetime(2022, 2, 20, 20, 36, 51, 423027), verbose_name='借出时间')),
                ('return_ddl', models.DateTimeField(default=datetime.datetime(2022, 2, 20, 20, 36, 51, 423027), verbose_name='归还期限')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='所借书籍')),
            ],
            options={
                'verbose_name': '借阅关系',
                'verbose_name_plural': '借阅关系',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_time', models.DateField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='用户名')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('borrowed_books', models.ManyToManyField(through='book.Borrow', to='book.Book', verbose_name='借阅书籍')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=60, verbose_name='书名')),
                ('author', models.CharField(max_length=60, verbose_name='作者')),
                ('publisher', models.CharField(max_length=60, verbose_name='出版社')),
                ('request_time', models.DateTimeField(default=datetime.datetime(2022, 2, 20, 20, 36, 51, 424018), verbose_name='申请时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='申请状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='申请者')),
            ],
            options={
                'verbose_name': '读者想看',
                'verbose_name_plural': '读者想看',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('request', models.CharField(max_length=128, verbose_name='申请书籍')),
                ('action', models.CharField(max_length=30, verbose_name='操作')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='相关书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.user', verbose_name='借阅者'),
        ),
    ]
