# Generated by Django 3.2.5 on 2022-02-19 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrow_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 14, 43, 49, 993802), verbose_name='借出时间'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_ddl',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 14, 43, 49, 993802), verbose_name='归还期限'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 14, 43, 49, 994799), verbose_name='申请时间'),
        ),
    ]
